apiVersion: v1
metadata:
  name: Playwright and Jest Sauce Labs
  tags:
    - e2e
    - release team
    - other tag
  build: Release Playwright
files:
  - ./test/
suites:
  - name: "Sauce Playwright test"
    match: ".*.(spec|test).js$"
    settings:
      browserName: "chromium"
image:
  base: saucelabs/stt-playwright-jest-node
  version: latest
sauce:
  region: eu-central-1
