
apiVersion: v1
metadata:
  name: TestCafe with Sauce Testrunner Toolkit
  tags:
    - e2e
    - release team
    - other tag
  build: Release TestCafe
files:
  - ./tests/
suites:
- name: Tests
  match: tests/(.*)+\.(spec|test)\.[jt]sx?
image:
  base: saucelabs/stt-testcafe-node
  version: latest
sauce:
  region: eu-central-1
