apiVersion: v1
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release Puppeteer
files:
  - ./tests/login.spec.js
suites:
  - name: "Sauce Puppeteer test"
    match: ".*.(spec|test).js$"
    settings:
      browserName: "chrome"
image:
  base: saucelabs/stt-puppeteer-jest-node
  version: latest
sauce:
  region: eu-central-1
